### ISSUE TITLE
ModuleNotFoundError: No module named 'gym'

### ISSUE THREAD

**Issue by ll7** [ll7/robot_sf_ll7#14]
```
~/git/robot_sf_ll7$ python examples/demo_offensive.py 
Traceback (most recent call last):
  File "/home/luttkule/git/robot_sf_ll7/examples/demo_offensive.py", line 28, in <module>
    training()
  File "/home/luttkule/git/robot_sf_ll7/examples/demo_offensive.py", line 13, in training
    model = PPO.load("./model/run_043", env=env)
  File "/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/base_class.py", line 677, in load
    data, params, pytorch_variables = load_from_zip_file(
  File "/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/save_util.py", line 433, in load_from_zip_file
    data = json_to_data(json_data, custom_objects=custom_objects)
  File "/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/save_util.py", line 164, in json_to_data
    deserialized_object = cloudpickle.loads(base64_object)
ModuleNotFoundError: No module named 'gym'
```

**Comment by ll7** [comment]
```
pipnstall gym
Collecting gym
  Using cached gym-0.26.2-py3-none-any.whl
Requirement already satisfied: numpy>=1.18.0 in ./.venv/lib/python3.10/site-packages (from gym) (1.26.4)
Requirement already satisfied: cloudpickle>=1.2.0 in ./.venv/lib/python3.10/site-packages (from gym) (3.0.0)
Requirement already satisfied: gym-notices>=0.0.4 in ./.venv/lib/python3.10/site-packages (from gym) (0.0.8)
Installing collected packages: gym
Successfully installed gym-0.26.2
(.venv) luttkule@imech156-u:~/git/robot_sf_ll7$ python examples/demo_offensive.py 
/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/vec_env/patch_gym.py:95: UserWarning: You loaded a model that was trained using OpenAI Gym. We strongly recommend transitioning to Gymnasium by saving that model again.
  warnings.warn(
/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/base_class.py:748: UserWarning: You are probably loading a model saved with SB3 < 1.7.0, we deactivated exact_match so you can save the model again to avoid issues in the future (see https://github.com/DLR-RM/stable-baselines3/issues/1233 for more info). Original error: Error(s) in loading state_dict for MultiInputActorCriticPolicy:
        Missing key(s) in state_dict: "pi_features_extractor.ray_extractor.0.weight", "pi_features_extractor.ray_extractor.0.bias", "pi_features_extractor.ray_extractor.3.weight", "pi_features_extractor.ray_extractor.3.bias", "pi_features_extractor.ray_extractor.6.weight", "pi_features_extractor.ray_extractor.6.bias", "pi_features_extractor.ray_extractor.9.weight", "pi_features_extractor.ray_extractor.9.bias", "vf_features_extractor.ray_extractor.0.weight", "vf_features_extractor.ray_extractor.0.bias", "vf_features_extractor.ray_extractor.3.weight", "vf_features_extractor.ray_extractor.3.bias", "vf_features_extractor.ray_extractor.6.weight", "vf_features_extractor.ray_extractor.6.bias", "vf_features_extractor.ray_extractor.9.weight", "vf_features_extractor.ray_extractor.9.bias".  
Note: the model should still work fine, this only a warning.
  warnings.warn(
```

**Comment by ll7** [comment]
The old models require the old gym environment.

**Comment by ll7** [comment]
This runs fine now because we install `gym` and `gymnasium. However, we should update the `demo` to `gymnasium`.
