### ISSUE TITLE
test_can_load_model_snapshot failed on `LeLuGPC` WSL2204.

### ISSUE THREAD

**Issue by ll7** [ll7/robot_sf_ll7#5]
```
==================================== FAILURES =====================================
__________________________ test_can_load_model_snapshot ___________________________

    def test_can_load_model_snapshot():
        MODEL_PATH = "./temp/ppo_model"
        MODEL_FILE = f"{MODEL_PATH}.zip"
        if os.path.exists(MODEL_FILE) and os.path.isfile(MODEL_FILE):
            os.remove(MODEL_FILE)
    
        n_envs = 2
>       vec_env = make_vec_env(lambda: RobotEnv(), n_envs=n_envs, vec_env_cls=SubprocVecEnv)

tests/sb3_test.py:21: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
.venv/lib/python3.10/site-packages/stable_baselines3/common/env_util.py:125: in make_vec_env
    vec_env = vec_env_cls([make_env(i + start_index) for i in range(n_envs)], **vec_env_kwargs)
.venv/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py:119: in __init__
    observation_space, action_space = self.remotes[0].recv()
/usr/lib/python3.10/multiprocessing/connection.py:250: in recv
    buf = self._recv_bytes()
/usr/lib/python3.10/multiprocessing/connection.py:414: in _recv_bytes
    buf = self._recv(4)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <multiprocessing.connection.Connection object at 0x7f8214564250>, size = 4
read = <built-in function read>

    def _recv(self, size, read=_read):
        buf = io.BytesIO()
        handle = self._handle
        remaining = size
        while remaining > 0:
>           chunk = read(handle, remaining)
E           ConnectionResetError: [Errno 104] Connection reset by peer

/usr/lib/python3.10/multiprocessing/connection.py:379: ConnectionResetError
------------------------------ Captured stderr call -------------------------------
Process ForkServerProcess-1:
Traceback (most recent call last):
  File "/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/vec_env/patch_gym.py", line 40, in _patch_env
    import shimmy
ModuleNotFoundError: No module named 'shimmy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/env_util.py", line 100, in _init
    env = _patch_env(env)
  File "/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/vec_env/patch_gym.py", line 42, in _patch_env
    raise ImportError(
ImportError: Missing shimmy installation. You provided an OpenAI Gym environment. Stable-Baselines3 (SB3) has transitioned to using Gymnasium internally. In order to use OpenAI Gym environments with SB3, you need to install shimmy (`pip install 'shimmy>=0.2.1'`).
Process ForkServerProcess-2:
Traceback (most recent call last):
  File "/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/vec_env/patch_gym.py", line 40, in _patch_env
    import shimmy
ModuleNotFoundError: No module named 'shimmy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/process.py", line 314, in _bootstrap
    self.run()
  File "/usr/lib/python3.10/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 29, in _worker
    env = _patch_env(env_fn_wrapper.var())
  File "/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/env_util.py", line 100, in _init
    env = _patch_env(env)
  File "/home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/vec_env/patch_gym.py", line 42, in _patch_env
    raise ImportError(
ImportError: Missing shimmy installation. You provided an OpenAI Gym environment. Stable-Baselines3 (SB3) has transitioned to using Gymnasium internally. In order to use OpenAI Gym environments with SB3, you need to install shimmy (`pip install 'shimmy>=0.2.1'`).
================================ warnings summary =================================
.venv/lib/python3.10/site-packages/stable_baselines3/common/logger.py:13
  /home/luttkule/git/robot_sf_ll7/.venv/lib/python3.10/site-packages/stable_baselines3/common/logger.py:13: DeprecationWarning: 
  Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
  (to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
  but was not found to be installed on your system.
  If this would cause problems for you,
  please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466
          
    import pandas

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
============================= short test summary info =============================
FAILED tests/sb3_test.py::test_can_load_model_snapshot - ConnectionResetError: [Errno 104] Connection reset by peer
==================== 1 failed, 47 passed, 1 warning in 26.98s =====================
```

**Comment by ll7** [comment]
upgraded and explicitly installed the modules
